---
title: "Mortalidade-Infantil"
author: "Rodolfo Viana"
date: "01-12-2015"
output: html_document
---

Com o intuito de fazer um levantamento sobre a mortalidade infantil no estado da Paraíba, foram feitas as seguintes analises

```{r}
library(ggplot2)
require(gridExtra)
library(gtable)
library(grid)
library(dplyr)
```

```{r}
pre_natal_2011 <- read.csv("data/Consult_pre-natal_PARAIBA_2011_sem_acento.csv", sep=";")
pre_natal_2012 <- read.csv("data/Consult_pre-natal_PARAIBA_2012_sem_acento.csv", sep=";")
pre_natal_2013 <- read.csv("data/Consult_pre-natal_PARAIBA_2013_sem_acento.csv", sep=";")

nascidos_vivos_2011 <- read.csv("data/NASCIDOS_VIVOS_PARAIBA_2011_sem_acento.csv", sep=";")
nascidos_vivos_2012 <- read.csv("data/NASCIDOS_VIVOS_PARAIBA_2012_sem_acento.csv", sep=";")
nascidos_vivos_2013 <- read.csv("data/NASCIDOS_VIVOS_PARAIBA_2013_sem_acento.csv", sep=";")

obitos_infantis_2011 <- read.csv("data/OBITOS_INFANTIS_PARAIBA_2011_sem_acento.csv", sep=";")
obitos_infantis_2012 <- read.csv("data/OBITOS_INFANTIS_PARAIBA_2012_sem_acento.csv", sep=";")
obitos_infantis_2013 <- read.csv("data/OBITOS_INFANTIS_PARAIBA_2013_sem_acento.csv", sep=";")

obitos_infantis_2012[,5] <-  NULL
```

```{r}
# Calcula a taxa de mortalidade
calcula_mortalidade <- function(df_obitos, df_nascidos_vivos){
  df_obitos$Municipio <- as.character(df_obitos$Municipio)
  obitos <- filter(df_obitos, Municipio == "Total")[,5]
  
  df_nascidos_vivos$Municipio <- as.character(df_nascidos_vivos$Municipio)
  nascidos_vivos <- filter(df_nascidos_vivos, Municipio == "Total")[,2]
  
  (obitos/nascidos_vivos) * 1000
}

mortalidade_2011 <- calcula_mortalidade(obitos_infantis_2011, nascidos_vivos_2011)
mortalidade_2012 <- calcula_mortalidade(obitos_infantis_2012, nascidos_vivos_2012)
mortalidade_2013 <- calcula_mortalidade(obitos_infantis_2013, nascidos_vivos_2013)

mortalidade <- data.frame(ano = c(2011, 2012, 2013),
                          taxa = c(mortalidade_2011, mortalidade_2012, mortalidade_2013))


m <- ggplot(data = mortalidade, aes(x=ano, y = taxa, group=1)) + 
  geom_line() +
  geom_point() + 
  labs(y='Taxa de Mortalidade', x='Ano', title = "Mortalidade Infantil") + 
  theme_classic() + 
  theme(axis.ticks = element_blank()) +
  scale_x_continuous(breaks=2011:2013)

png("plot/mortalidade.png", width = 800, height = 600)
m
dev.off()
```

```{r}
totalConsultas <- function(data) {
  data[,3] <- as.numeric(as.character(data[,3]))
  data[,4] <- as.numeric(as.character(data[,4]))
  data[,5] <- as.numeric(as.character(data[,5]))
  
  data[is.na(data)] <- 0
  
  data$totalConsultas <- data[,3] + data[,4] + data[,5]
  tail(data, 1)$totalConsultas
}

pre_natal_2011_total <- totalConsultas(pre_natal_2011)
pre_natal_2012_total <- totalConsultas(pre_natal_2012)
pre_natal_2013_total <- totalConsultas(pre_natal_2013)

pre_natal <- data.frame(ano = c(2011, 2012, 2013),
                          consultas = c(pre_natal_2011_total, pre_natal_2012_total, pre_natal_2013_total))


p <- ggplot(data = pre_natal, aes(x=ano, y = consultas, group=1)) + 
  geom_line() +
  geom_point() + 
  labs(y='Total de Pacientes Atendidos', x='Ano', title = "Consultas Pré-Natal") + 
  theme_classic() + 
  theme(axis.ticks = element_blank()) +
  scale_x_continuous(breaks=2011:2013)

png("plot/pre_natal.png", width = 800, height = 600)
p
dev.off()
```


```{r}
grid.arrange(p, m, ncol=2)
png("plot/comparacao.png", width = 800, height = 600)
dev.off()
```